# Generated by Django 6.0 on 2026-01-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'group',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('course', models.CharField(blank=True, max_length=10, null=True)),
                ('course_format', models.CharField(blank=True, max_length=15, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('alreadyPaid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('utm', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('manager', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-id',),
            },
        ),
    ]
