# Generated by Django 6.0 on 2026-01-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.IntegerField(blank=True)),
                ('course', models.CharField(max_length=10)),
                ('course_format', models.CharField(max_length=15)),
                ('course_type', models.CharField(max_length=100)),
                ('sum', models.IntegerField(blank=True)),
                ('alreadyPaid', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utm', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('manager', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-id',),
            },
        ),
    ]
