# Generated by Django 6.0 on 2026-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_commentmodel_order_alter_ordersmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='groupName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
