# Generated by Django 6.0 on 2026-01-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersmodel_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='groupName',
        ),
    ]
