# Generated by Django 6.0 on 2026-01-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ordersmodel_groupname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersmodel',
            options={'ordering': ('id',)},
        ),
    ]
